### ISSUE TITLE
Share buttons display abnormally

### ISSUE THREAD

**Issue by jia-dai** [utopian-io/utopian.io#268]
#### Expected behavior
All the share icon buttons should be displayed normally inside the box.

#### Actual behavior
By clicking on `Share` link of each article, the media buttons are out of the box, this breaks the layout.

#### How to reproduce
Open an article/post, and click on `Share`, the icon buttons displaying out of range.

* Browser: Chrome 63 (Edge is working well)
* Operating system: Windows 10 64bit

#### Recording Of The Bug
Following is a screenshot under Chrome 63.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516245384/o1gp4fypqxrzblvc0qiy.png)
Following is a screenshot under Edge, which displaying well.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516327162/ss2kafdq47xmkw5cws2o.png)

#### Suggestions
I noticed there are some `<br>` after the buttons, and the `margin` value is different between Chrome and Edge. However I can't provide more on how to correct this, I think this is a systematic change since utopian.io is a complex project.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516246142/dbc05wfluyemjaituogz.png)
Margin value is  `24` under Chrome 63.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516246372/bpt4cufosp94wn5hyvtv.png)
Margin value is `3.2` under Edge, which displaying normally.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@daijia/share-buttons-display-abnormally">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ashispavan** [comment]
Not able to reproduce this issue in Chrome 63. Please verify.

**Comment by jia-dai** [comment]
I've tried on another computer with Chrome 63 and Windows 10 64bit, the
problem is still there.
My OS version: Windows 10 Professional 64bit (1709 v16299.192)
My Chrome detail version: 63.0.3239.132



Ashis Pavan <notifications@github.com>于2018年1月21日周日 上午12:22写道：

**Comment by JohannesKnecht** [comment]
Seems to have been fixed right ?

**Comment by jia-dai** [comment]
no I'm afraid it's not.
I even tried to clean cache of browser and test on another computer, the
problem is always there.
Have you tried on Chrome 63 (64 bit) and Windows 10 (64 bit)?

Johannes Knecht <notifications@github.com>于2018年1月21日周日 下午7:02写道：

**Comment by IAMZERG** [comment]
Tried reproducing this on Windows 10 & Chrome Version 64.0.3282.140 (Official Build) (64-bit)
Not seeing this issue on my computer.  Looks normal.

Anyone else still getting this?  Get screenshot w/ copy/paste of the HTML of the page?

**Comment by jia-dai** [comment]
I looked deeper into this issue. The problem is a setting of Chrome on
minimum font size.
1) For Chinese version Chrome, the minimum font size is set to 12px for
reading ability.
2) The element of *<br>* is set a margin of *2em*.
3) Thus the margin value of <br> will be 24px in Chrome Chinese version.
4) It will lead to a display abnormal as mentioned.
I tried to set the minimum font size to 6px and the margin becomes thinner.
There is also a CSS hack using transform: scale(0.1), but seems not working
for this case.
A simple way to optimize this is to set the margin value to a px rather
than em.
Besides, maybe Japanese and Korean version would face with this same issue.

Wes <notifications@github.com>于2018年2月4日周日 上午11:29写道：
